### ISSUE TITLE
messagekey should be a string, not cluster module

### ISSUE THREAD

**Issue by objectiveSee** [sirian/node-cluster-hub#4]
In the README, you initialize Hub by passing in the cluster module as the parameter.  This sets `this.messageKey` to whatever is exported from the cluster module. In my case, this causes a crash when sending messages because of the following error:

```
    var string = JSON.stringify(message) + '\n';
                      ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at process.target._send (child_process.js:479:23)
    at process.target.send (child_process.js:416:12)
    at Worker.send (cluster.js:64:21)
    at Hub.sendToMaster (/Users/danny/workspace/easerver/node_modules/cluster-hub/lib/Hub.js:128:24)
    at Hub.doRequest (/Users/danny/workspace/easerver/node_modules/cluster-hub/lib/Hub.js:212:5)
    at Hub.requestMaster (/Users/danny/workspace/easerver/node_modules/cluster-hub/lib/Hub.js:150:10)
```

The solution IMO is to pass a string or no parameter at all when initializing Hub(). I suggest updating the README to reflect this.

**Comment by sirian** [comment]
@objectiveSee updated readme https://github.com/sirian/node-cluster-hub/commit/14bbdf9875787ef18b7bba071058dfec05b284b3

**Comment by yeahoffline** [comment]
still wrong @ https://www.npmjs.com/package/cluster-hub

**Comment by sirian** [comment]
bumped new version to npmjs
